run:
  go: 1.21
  timeout: 5m

linters:
  enable:
    #- deadcode # Temporarily disabling this while spinning up the service
    - bodyclose
    - dogsled
    - dupl
    - exhaustive
    - gosimple
    - nakedret
    - noctx
    - stylecheck
    - unconvert
    - unparam
    - whitespace
    - structcheck
    - goconst
    - gocritic
    - exportloopref
    - goprintffuncname
    - ineffassign
    - gocyclo
    - funlen
    - errcheck
    - goimports
    - revive
    - govet
    - unconvert
    - varcheck
    - staticcheck
  disable:
    - deadcode
    - unused
    - typecheck

linters-settings:
  govet:
    check-shadowing: true
  dupl:
    threshold: 100
  gci:
    local-prefixes: github.com/o1egl/pidor-bot
  goimports:
    local-prefixes: github.com/o1egl/pidor-bot
  gocyclo:
    min-complexity: 15
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 2
  exhaustive:
    default-signifies-exhaustive: true
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - hugeParam

issues:
  # List of regexps of issue texts to exclude, empty list by default.
  # But independently from this option we use default exclude patterns,
  # it can be disabled by `exclude-use-default: false`. To list all
  # excluded by default patterns execute `golangci-lint run --help`
  exclude:
    - exported func .* returns unexported type .*, which can be annoying to use
  exclude-rules:
    - path: _test\.go
      linters:
        - bodyclose
        - gomnd
        - noctx
        - goconst
        - funlen
        - gocyclo
        - dupl
    - path: pkg/selftest/
      linters:
        - bodyclose
        - gomnd
        - noctx
        - goconst
        - funlen
        - gocyclo
        - dupl
    - text: "shadow: declaration of \"err\" shadows declaration"
      linters:
        - govet
    - text: "shadow: declaration of \"ctx\" shadows declaration"
      linters:
        - govet
