version: '3'

includes:
  deps:
    taskfile: ./tools/Taskfile.yaml
    dir: ./tools

env:
  TOOLS_BIN:
    sh: echo "$(pwd)/tools/bin"

tasks:
  default:
    cmds:
      - task -l

  build:
    desc: Build the app
    cmds:
      - go build -o bin/pidor-bot

  generate:
    desc: Run code generators
    deps: [deps:mockgen, deps:go-enum]
    cmds:
      - go generate ./...

  fmt:
    desc: Run go fmt
    cmds:
      - goimports -w -local github.com/o1egl/pidor-bot ./..

  lint:
    desc: Run linters
    deps: [deps:golangci-lint]
    cmds:
      - ./tools/bin/golangci-lint run -v